# Nombre del workflow (lo verás en GitHub Actions)
name: Android CI

# Define cuándo se ejecuta este workflow:
on:
  push:  # Cuando alguien hace un push (sube cambios)
    branches: [ "ci/cd", "master" ]  # Solo si es a las ramas "ci/cd" o "master"
  pull_request:  # Cuando se crea o actualiza un pull request
    branches: [ "ci/cd", "master" ]  # Solo si el PR apunta a "ci/cd" o "master"

# Aquí empiezan los trabajos (jobs) a ejecutar
jobs:
  build:  # Nombre del job
    runs-on: ubuntu_latest  # Se ejecuta en una máquina virtual Ubuntu (última versión)

    steps:
      # Paso 1: Descarga el código del repo en la máquina virtual
      - uses: actions/checkout@v3

      # Paso 2: Configura Java JDK 11 (requerido por Android para compilar)
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Versión del JDK
          distribution: 'temurin'  # Distribución del JDK (Temurin = OpenJDK confiable)
          cache: gradle  # Activa cacheo para Gradle (acelera builds)

      # Paso 3: Configura Gradle para que use caching y comandos correctos
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Paso 4: Construye (compila) la app usando Gradle
      - name: Build app
        run: ./gradlew assemble  # Ejecuta el comando assemble de Gradle (genera APKs)
